/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './editor.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/editor/editor.component';
import * as i3 from '../../../node_modules/ng2-ace-editor/src/component.ngfactory';
import * as i4 from '@angular/forms';
import * as i5 from 'ng2-ace-editor/src/component';
const styles_EditorComponent:any[] = [i0.styles];
export const RenderType_EditorComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_EditorComponent,data:{}});
export function View_EditorComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'ace-editor',([] as any[]),
      (null as any),[[(null as any),'textChanged'],[(null as any),'textChange']],(_v,
          en,$event) => {
        var ad:boolean = true;
        var _co:i2.EditorComponent = _v.component;
        if (('textChanged' === en)) {
          const pd_0:any = ((<any>_co.contentChange()) !== false);
          ad = (pd_0 && ad);
        }
        if (('textChange' === en)) {
          const pd_1:any = ((<any>(_co.content = $event)) !== false);
          ad = (pd_1 && ad);
        }
        return ad;
      },i3.View_AceEditorComponent_0,i3.RenderType_AceEditorComponent)),i1.ɵprd(5120,
      (null as any),i4.NG_VALUE_ACCESSOR,(p0_0:any) => {
        return [p0_0];
      },[i5.AceEditorComponent]),i1.ɵdid(114688,(null as any),0,i5.AceEditorComponent,
      [i1.ElementRef],{options:[0,'options'],theme:[1,'theme'],mode:[2,'mode'],text:[3,
          'text']},{textChanged:'textChanged',textChange:'textChange'}),(_l()(),i1.ɵted((null as any),
      ['\n    \n']))],(_ck,_v) => {
    var _co:i2.EditorComponent = _v.component;
    const currVal_0:any = _co.options;
    const currVal_1:any = 'eclipse';
    const currVal_2:any = _co.mode;
    const currVal_3:any = _co.content;
    _ck(_v,2,0,currVal_0,currVal_1,currVal_2,currVal_3);
  },(null as any));
}
export function View_EditorComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-editor',([] as any[]),
      (null as any),(null as any),(null as any),View_EditorComponent_0,RenderType_EditorComponent)),
      i1.ɵdid(4308992,(null as any),0,i2.EditorComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const EditorComponentNgFactory:i1.ComponentFactory<i2.EditorComponent> = i1.ɵccf('app-editor',
    i2.EditorComponent,View_EditorComponent_Host_0,{mode:'mode',content:'content'},
    {contentEvent:'contentChange'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9jb2RlcnVuL3NyYy9hcHAvZWRpdG9yL2VkaXRvci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc2FudG9zaC9Qcm9qZWN0cy9hbmd1bGFyL2NvZGVydW4vc3JjL2FwcC9lZGl0b3IvZWRpdG9yLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9jb2RlcnVuL3NyYy9hcHAvZWRpdG9yL2VkaXRvci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9jb2RlcnVuL3NyYy9hcHAvZWRpdG9yL2VkaXRvci5jb21wb25lbnQudHMuRWRpdG9yQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFjZS1lZGl0b3IgKHRleHRDaGFuZ2VkKT1cImNvbnRlbnRDaGFuZ2UoKVwiIFxuW3RoZW1lXT1cIidlY2xpcHNlJ1wiXG5bKHRleHQpXT1cImNvbnRlbnRcIlxuW21vZGVdPW1vZGUgXG5bb3B0aW9uc109XCJvcHRpb25zXCI+XG4gICAgXG48L2FjZS1lZGl0b3I+IiwiPGFwcC1lZGl0b3I+PC9hcHAtZWRpdG9yPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO21CQUFBO1FBQUE7UUFBQTtRQUFZO1VBQUE7VUFBQTtRQUFBO1FBRVo7VUFBQTtVQUFBO1FBQUE7UUFGQTtNQUFBO01BQUE7UUFBQTtNQUFBLGtDQUFBO01BQUE7VUFBQSw4REFJb0I7TUFBQTs7SUFBcEI7SUFIQTtJQUVBO0lBREE7SUFGQSxXQUlBLFVBSEEsVUFFQSxVQURBLFNBRkE7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7SUFBQTs7Ozs7In0=
