/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './demo.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/demo/demo.component';
const styles_DemoComponent:any[] = [i0.styles];
export const RenderType_DemoComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_DemoComponent,data:{}});
export function View_DemoComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  demo works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_DemoComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-demo',([] as any[]),
      (null as any),(null as any),(null as any),View_DemoComponent_0,RenderType_DemoComponent)),
      i1.ɵdid(114688,(null as any),0,i2.DemoComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DemoComponentNgFactory:i1.ComponentFactory<i2.DemoComponent> = i1.ɵccf('app-demo',
    i2.DemoComponent,View_DemoComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9jb2RlcnVuL3NyYy9hcHAvZGVtby9kZW1vLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zYW50b3NoL1Byb2plY3RzL2FuZ3VsYXIvY29kZXJ1bi9zcmMvYXBwL2RlbW8vZGVtby5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9zYW50b3NoL1Byb2plY3RzL2FuZ3VsYXIvY29kZXJ1bi9zcmMvYXBwL2RlbW8vZGVtby5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9jb2RlcnVuL3NyYy9hcHAvZGVtby9kZW1vLmNvbXBvbmVudC50cy5EZW1vQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGRlbW8gd29ya3MhXG48L3A+XG4iLCI8YXBwLWRlbW8+PC9hcHAtZGVtbz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLHVDQUVDO01BQUE7OztvQkNGSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
