/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from '../../node_modules/clarity-angular/clarity-angular.ngfactory';
import * as i4 from './app.component.ngfactory';
import * as i5 from '@angular/common';
import * as i6 from '@angular/platform-browser';
import * as i7 from '@angular/forms';
import * as i8 from 'clarity-angular';
import * as i9 from 'ng2-ace-editor/src/module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.ɵczNgFactory,i4.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i5.NgLocalization,i5.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i6.DomSanitizer,
              i6.ɵe,[i5.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i6.DomSanitizer]),
          i0.ɵmpd(4608,i6.HAMMER_GESTURE_CONFIG,i6.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i6.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i6.ɵDomEventsPlugin(p0_0),new i6.ɵKeyEventsPlugin(p1_0),new i6.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i5.DOCUMENT,i5.DOCUMENT,i5.DOCUMENT,i6.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i6.EventManager,i6.EventManager,[i6.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i6.ɵDomSharedStylesHost,i6.ɵDomSharedStylesHost,[i5.DOCUMENT]),
          i0.ɵmpd(4608,i6.ɵDomRendererFactory2,i6.ɵDomRendererFactory2,[i6.EventManager,
              i6.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i6.ɵDomRendererFactory2]),i0.ɵmpd(6144,i6.ɵSharedStylesHost,(null as any),
              [i6.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i6.Meta,i6.Meta,[i5.DOCUMENT]),i0.ɵmpd(4608,
              i6.Title,i6.Title,[i5.DOCUMENT]),i0.ɵmpd(4608,i7.ɵi,i7.ɵi,([] as any[])),
          i0.ɵmpd(4608,i8.ÇlrFocusTrapTracker,i8.ÇlrFocusTrapTracker,([] as any[])),
          i0.ɵmpd(5120,i8.ɵcv,i8.ɵcw,[[3,i8.ɵcv]]),i0.ɵmpd(512,i5.CommonModule,i5.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i6.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any) => {
                return [i6.ɵc(p0_0,p0_1)];
              },[[2,i6.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i6.BrowserModule,i6.BrowserModule,[[3,i6.BrowserModule]]),i0.ɵmpd(512,
              i7.ɵba,i7.ɵba,([] as any[])),i0.ɵmpd(512,i7.FormsModule,i7.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i9.AceEditorModule,i9.AceEditorModule,([] as any[])),
          i0.ɵmpd(512,i8.ClrIconModule,i8.ClrIconModule,([] as any[])),i0.ɵmpd(512,
              i8.ɵb,i8.ɵb,([] as any[])),i0.ɵmpd(512,i8.ɵk,i8.ɵk,([] as any[])),i0.ɵmpd(512,
              i8.ClrDropdownModule,i8.ClrDropdownModule,([] as any[])),i0.ɵmpd(512,
              i8.ClrAlertModule,i8.ClrAlertModule,([] as any[])),i0.ɵmpd(512,i8.ClrEmphasisModule,
              i8.ClrEmphasisModule,([] as any[])),i0.ɵmpd(512,i8.ClrFormsModule,i8.ClrFormsModule,
              ([] as any[])),i0.ɵmpd(512,i8.ClrLoadingModule,i8.ClrLoadingModule,([] as any[])),
          i0.ɵmpd(512,i8.ɵt,i8.ɵt,([] as any[])),i0.ɵmpd(512,i8.ɵce,i8.ɵce,([] as any[])),
          i0.ɵmpd(512,i8.ClrDatagridModule,i8.ClrDatagridModule,([] as any[])),i0.ɵmpd(512,
              i8.ClrStackViewModule,i8.ClrStackViewModule,([] as any[])),i0.ɵmpd(512,
              i8.ClrTreeViewModule,i8.ClrTreeViewModule,([] as any[])),i0.ɵmpd(512,
              i8.ClrDataModule,i8.ClrDataModule,([] as any[])),i0.ɵmpd(512,i8.ɵcl,
              i8.ɵcl,([] as any[])),i0.ɵmpd(512,i8.ClrModalModule,i8.ClrModalModule,
              ([] as any[])),i0.ɵmpd(512,i8.ClrLoadingButtonModule,i8.ClrLoadingButtonModule,
              ([] as any[])),i0.ɵmpd(512,i8.ClrButtonGroupModule,i8.ClrButtonGroupModule,
              ([] as any[])),i0.ɵmpd(512,i8.ClrButtonModule,i8.ClrButtonModule,([] as any[])),
          i0.ɵmpd(512,i8.ClrSyntaxHighlightModule,i8.ClrSyntaxHighlightModule,([] as any[])),
          i0.ɵmpd(512,i8.ɵcu,i8.ɵcu,([] as any[])),i0.ɵmpd(512,i8.ClrMainContainerModule,
              i8.ClrMainContainerModule,([] as any[])),i0.ɵmpd(512,i8.ClrNavigationModule,
              i8.ClrNavigationModule,([] as any[])),i0.ɵmpd(512,i8.ɵcx,i8.ɵcx,([] as any[])),
          i0.ɵmpd(512,i8.ClrTabsModule,i8.ClrTabsModule,([] as any[])),i0.ɵmpd(512,
              i8.ɵde,i8.ɵde,([] as any[])),i0.ɵmpd(512,i8.ClrLayoutModule,i8.ClrLayoutModule,
              ([] as any[])),i0.ɵmpd(512,i8.ɵdp,i8.ɵdp,([] as any[])),i0.ɵmpd(512,
              i8.ClrTooltipModule,i8.ClrTooltipModule,([] as any[])),i0.ɵmpd(512,i8.ClrPopoverModule,
              i8.ClrPopoverModule,([] as any[])),i0.ɵmpd(512,i8.ClrWizardModule,i8.ClrWizardModule,
              ([] as any[])),i0.ɵmpd(512,i8.ClarityModule,i8.ClarityModule,([] as any[])),
          i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NhbnRvc2gvUHJvamVjdHMvYW5ndWxhci9jb2RlcnVuL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zYW50b3NoL1Byb2plY3RzL2FuZ3VsYXIvY29kZXJ1bi9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
